M48
; DRILL file {KiCad 7.0.1-0} date 2023 April 02, Sunday 15:37:21
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-02T15:37:21-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X91.6Y-64.24
X91.6Y-70.02
T2
X89.17Y-55.65
X89.17Y-80.65
X161.17Y-55.65
X161.17Y-80.65
T0
M30
